language: node_js
node_js:
  - '0.10'
  - '0.11'
addons:
  code_climate:
    repo_token:
      secure: N2YPsBcB+T5QYENXooHyJ4RJ3RQNhVIOdjr6OPtgJgQSbqP0nAtKxxlXptPNE+Y+CsS6tU9KMECkw7PI0mEJ6ylICXwTnXr+8oGWOjjXwYD/2JG8TBRuha4vpH9JMEKs8jNsUce3m1UJlDjGHnkrtNBOmiRUBWjRnTj8MfU+zP4=
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
after_script:
  - istanbul cover _mocha -- --recursive
  - codeclimate < ./coverage/lcov.info
services: mongodb
